### ISSUE TITLE
Feature Request: Optional breadcrumb separator instead of slash

### ISSUE THREAD

**Issue by sub-atomic** [jdeal/obsidian-path-title-plugin#2]
So thankful that you made this plugin. My only request would be to add the option of using " > " instead of "/" as the separator. For whatever reason it's easier for me to parse the path at a glance when it's separated by a > than with a slash. 

Is it possible for me to edit the main.js or the css file to accomplish this?

**Comment by sub-atomic** [comment]
Nevermind, I figured out how to do it by using the Text Replacement feature! Awesome! Thanks!

**Comment by jdeal** [comment]
@sub-atomic Glad the text replacement worked for you! That’s a great use case. Note that the folder replacement depends on the slashes in a path, so if you use any of those, you’ll want your slash replacement to be after those.
